schema: "classroom50/repo-config/v1"
classroom: "cu-csci3308-fall2026"
assignment: "lab-3-gui-development"
owner:
  username: "saanvitrivedi"
  id: 43284221
  accepted_at: "2026-09-10T17:59:35Z"
source:
  owner: "CUBoulder-CSCI-3308-Fall2026"
  owner_id: 319159502
  repo: "lab-3-gui-development"
  branch: "main"
